# Generated by Django 5.0.3 on 2024-04-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('major', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('expired_time', models.DateTimeField()),
                ('salary', models.DecimalField(decimal_places=1, max_digits=3)),
                ('description', models.CharField(max_length=2000)),
                ('level', models.CharField(choices=[('IN', 'Intern'), ('FR', 'Fresher'), ('JR', 'Junior'), ('MD', 'Middle'), ('SR', 'Senior'), ('MG', 'Manager'), ('CH', 'Chief')], max_length=2)),
                ('major', models.ManyToManyField(to='major.major')),
            ],
        ),
    ]
