# Generated by Django 5.0.3 on 2024-05-02 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobs_job_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='expired_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
