# Generated by Django 5.0.3 on 2024-05-02 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('jobs', '0003_alter_jobs_expired_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='job_address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.address'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='salary',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
    ]
