# Generated by Django 5.0.3 on 2024-05-02 19:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_jobs_job_address_alter_jobs_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='level',
            field=models.CharField(choices=[('IN', 'Intern'), ('FR', 'Fresher'), ('JR', 'Junior'), ('MD', 'Middle'), ('SR', 'Senior'), ('MG', 'Manager'), ('CH', 'Chief')], max_length=2, null=True),
        ),
    ]
