# Generated by Django 5.0.3 on 2024-05-03 20:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_jobs_id_alter_jobs_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobs',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
