# Generated by Django 5.0.3 on 2024-05-03 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_jobs_created_at_jobs_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='updated_at',
        ),
    ]
