# Generated by Django 5.0.3 on 2024-05-14 17:58

import uuid
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_remove_company_created_at_remove_company_updated_at_and_more'),
        ('jobs', '0009_alter_jobs_created_at_alter_jobs_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='company',
            field=models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
            preserve_default=False,
        ),
    ]
