# Generated by Django 5.0.3 on 2024-05-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0014_alter_employee_cv'),
        ('jobs', '0010_jobs_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='cv',
            field=models.FileField(default=1, upload_to='cv/%Y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobs',
            name='prefer_jobs',
            field=models.ManyToManyField(to='employee.employee'),
        ),
    ]
