# Generated by Django 5.0.3 on 2024-05-17 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0014_alter_employee_cv'),
        ('jobs', '0011_jobs_cv_jobs_prefer_jobs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='cv',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='prefer_jobs',
        ),
        migrations.AddField(
            model_name='jobs',
            name='applied_jobs',
            field=models.ManyToManyField(blank=True, null=True, to='employee.employee'),
        ),
    ]
