# Generated by Django 5.0.3 on 2024-05-19 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_remove_jobs_cv_remove_jobs_prefer_jobs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='salary',
        ),
        migrations.AddField(
            model_name='jobs',
            name='max_salary',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='min_salary',
            field=models.IntegerField(null=True),
        ),
    ]
