# Generated by Django 5.0.3 on 2024-03-31 08:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '__first__'),
        ('jobs', '0001_initial'),
        ('major', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('number', models.CharField(max_length=128)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('personal_introduction', models.CharField(max_length=2000)),
                ('level', models.CharField(choices=[('IN', 'Intern'), ('FR', 'Fresher'), ('JR', 'Junior'), ('MD', 'Middle'), ('SR', 'Senior'), ('MG', 'Manager'), ('CH', 'Chief')], max_length=2)),
                ('min_salary', models.DecimalField(decimal_places=1, max_digits=3)),
                ('max_salary', models.DecimalField(decimal_places=1, max_digits=3)),
                ('employee_address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_address', to='base.address')),
                ('major', models.ManyToManyField(to='major.major')),
                ('prefer_jobs', models.ManyToManyField(to='jobs.jobs')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
