# Generated by Django 5.0.3 on 2024-05-03 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employee_options_alter_employee_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='registration_method',
            field=models.CharField(choices=[('username', 'Username'), ('google', 'Google')], default='google', max_length=10),
        ),
    ]
