# Generated by Django 4.2.13 on 2024-05-08 06:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_employee_registration_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='cv',
            field=models.FileField(default=django.utils.timezone.now, upload_to='cv/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
