# Generated by Django 5.0.3 on 2024-05-16 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_employee_user_alter_employee_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='prefer_jobs',
        ),
    ]
