# Generated by Django 5.0.3 on 2024-05-17 16:45

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_remove_employee_prefer_jobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='cv',
            field=models.FileField(upload_to=builtins.id),
        ),
    ]
