# Generated by Django 5.0.3 on 2024-05-19 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0016_remove_employee_last_login_remove_employee_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='max_salary',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='min_salary',
            field=models.IntegerField(null=True),
        ),
    ]
