# Generated by Django 5.0.3 on 2024-05-03 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('major', '0002_major_created_at_major_updated_at_alter_major_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='major',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='major',
            name='updated_at',
        ),
    ]
