# Generated by Django 5.0.3 on 2024-04-15 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=300)),
                ('district', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=200)),
                ('zipcode', models.IntegerField()),
            ],
        ),
    ]
