# Generated by Django 5.0.3 on 2024-05-03 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_address_created_at_address_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='address',
            name='updated_at',
        ),
    ]
