# Generated by Django 5.0.3 on 2024-04-15 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '__first__'),
        ('major', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('personal_introduction', models.CharField(max_length=2000)),
                ('company_address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='address.address')),
                ('major', models.ManyToManyField(to='major.major')),
            ],
        ),
    ]
