# Generated by Django 5.0.3 on 2024-05-03 20:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_remove_company_created_at_remove_company_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 2, 20, 36, 35, 710076, tzinfo=datetime.timezone.utc), verbose_name='expiration time (of ad)'),
        ),
        migrations.AddField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 2, 20, 36, 35, 710093, tzinfo=datetime.timezone.utc), verbose_name='expiration time (of ad)'),
        ),
    ]
