# Generated by Django 5.0.3 on 2024-05-14 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_alter_company_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='email',
        ),
        migrations.RemoveField(
            model_name='company',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='company',
            name='password',
        ),
    ]
